using System.IO;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;

namespace Sdk.Editor.Scripts.Addressable
{
    public static class GenerateGameVersionTool
    {
        private static string codeFilePath = "Assets/Sdk/Runtime/Base/GameVersion.cs";
     
        public static bool GenerateGameVersionCodeFile(string gameVersion,LaunchSettings.EnvironmentType gameEnv)
        {
            // 定义 自动生成部分的代码
            var gameVersionCode = $@"
//------------------------------------------------------------------------------
// <auto-generated>
//   打包工具会修改该文件，手动修改内容可能会丢失修改
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable once CheckNamespace
namespace Sdk.Runtime.Base   
{{
    /// <summary>
    /// 游戏版本号
    /// </summary>
    public static class GameVersion
    {{
        public const string GameVer = ""{gameVersion}"";

        public const LaunchSettings.EnvironmentType GameEnv = LaunchSettings.EnvironmentType.{gameEnv};
    }}
}}
";
            
            // 写入 sdk程序集里的版本号 的代码
            File.WriteAllText(codeFilePath, gameVersionCode);
            
            
            AssetDatabase.ImportAsset(codeFilePath);
            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
            return true;
        }

        /// <summary>
        /// 输出生成的脚本内容
        /// </summary>
        public static void OutputCodeContent()
        {
            if (File.Exists(codeFilePath))
            {
                string scriptContent = File.ReadAllText(codeFilePath);
                Debug.Log(scriptContent);
            }
            else
            {
                Debug.LogError("File not found: " + codeFilePath);
            }
        }
    }
}
