// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: Server/server.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务器内部Nats请求Orleans的消息
type NatsOrleansRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpCode   int32  `protobuf:"varint,1,opt,name=opCode,proto3" json:"opCode,omitempty"`    // 消息 Id
	GrainKey string `protobuf:"bytes,2,opt,name=grainKey,proto3" json:"grainKey,omitempty"` // key
	MsgData  []byte `protobuf:"bytes,3,opt,name=msgData,proto3" json:"msgData,omitempty"`   // 来自客户端或使用 protobuf 打包后的消息体数据
}

func (x *NatsOrleansRequest) Reset() {
	*x = NatsOrleansRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Server_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NatsOrleansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsOrleansRequest) ProtoMessage() {}

func (x *NatsOrleansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Server_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsOrleansRequest.ProtoReflect.Descriptor instead.
func (*NatsOrleansRequest) Descriptor() ([]byte, []int) {
	return file_Server_server_proto_rawDescGZIP(), []int{0}
}

func (x *NatsOrleansRequest) GetOpCode() int32 {
	if x != nil {
		return x.OpCode
	}
	return 0
}

func (x *NatsOrleansRequest) GetGrainKey() string {
	if x != nil {
		return x.GrainKey
	}
	return ""
}

func (x *NatsOrleansRequest) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

// 服务器内部Nats请求Orleans的消息
type NatsOrleansResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"` // 0成功，404未找到
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`    // 错误消息
	MsgData []byte `protobuf:"bytes,3,opt,name=msgData,proto3" json:"msgData,omitempty"`  // 返回的 protobuf 消息体数据
}

func (x *NatsOrleansResponse) Reset() {
	*x = NatsOrleansResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Server_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NatsOrleansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsOrleansResponse) ProtoMessage() {}

func (x *NatsOrleansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Server_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsOrleansResponse.ProtoReflect.Descriptor instead.
func (*NatsOrleansResponse) Descriptor() ([]byte, []int) {
	return file_Server_server_proto_rawDescGZIP(), []int{1}
}

func (x *NatsOrleansResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *NatsOrleansResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *NatsOrleansResponse) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

var File_Server_server_proto protoreflect.FileDescriptor

var file_Server_server_proto_rawDesc = []byte{
	0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x62, 0x0a, 0x12, 0x4e, 0x61, 0x74, 0x73, 0x4f, 0x72, 0x6c, 0x65, 0x61, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d,
	0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x22, 0x61, 0x0a, 0x13, 0x4e, 0x61, 0x74, 0x73, 0x4f, 0x72,
	0x6c, 0x65, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Server_server_proto_rawDescOnce sync.Once
	file_Server_server_proto_rawDescData = file_Server_server_proto_rawDesc
)

func file_Server_server_proto_rawDescGZIP() []byte {
	file_Server_server_proto_rawDescOnce.Do(func() {
		file_Server_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_Server_server_proto_rawDescData)
	})
	return file_Server_server_proto_rawDescData
}

var file_Server_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Server_server_proto_goTypes = []interface{}{
	(*NatsOrleansRequest)(nil),  // 0: ClientProto.NatsOrleansRequest
	(*NatsOrleansResponse)(nil), // 1: ClientProto.NatsOrleansResponse
}
var file_Server_server_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Server_server_proto_init() }
func file_Server_server_proto_init() {
	if File_Server_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Server_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NatsOrleansRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Server_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NatsOrleansResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Server_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Server_server_proto_goTypes,
		DependencyIndexes: file_Server_server_proto_depIdxs,
		MessageInfos:      file_Server_server_proto_msgTypes,
	}.Build()
	File_Server_server_proto = out.File
	file_Server_server_proto_rawDesc = nil
	file_Server_server_proto_goTypes = nil
	file_Server_server_proto_depIdxs = nil
}
