
// <auto-generated>
//     Generated by the ui framework.  DO NOT EDIT!
//     Date time: 2024-06-21 14:18:18
//     Remark: 可以另写一个文件来扩展此类来绑定 UI 控件, 实现 UI View 相关的逻辑
// </auto-generated>

using UIFramework.UIScreen;
using UnityEngine;
// ReSharper disable once CheckNamespace
namespace MyUI
{
    /// <summary>
    /// Toast 的 View 类   
    /// </summary>
    public sealed partial class ToastScreenView : UIScreenViewBase
    {
        
    }
}
