
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ClientCfg.cfg
{ 
    public enum EActivityType
    {
        /// <summary>
        /// 无效的活动类型
        /// </summary>
        Invalid = 1,
        /// <summary>
        /// 话题 pk 活动
        /// </summary>
        Topic = 2,
    }

} 

