
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ClientCfg.cfg
{ 
    public enum EDressType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 头发
        /// </summary>
        Hair = 1,
        /// <summary>
        /// 面部
        /// </summary>
        Face = 2,
        /// <summary>
        /// 上身
        /// </summary>
        Cloth = 3,
        /// <summary>
        /// 下身
        /// </summary>
        Pants = 4,
        /// <summary>
        /// 帽子
        /// </summary>
        Hat = 5,
        /// <summary>
        /// 手
        /// </summary>
        Hand = 6,
    }

} 

