
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ClientCfg.cfg
{ 
    public enum EGainType
    {
        /// <summary>
        /// 官方关卡获得
        /// </summary>
        OfficialStage = 1,
        /// <summary>
        /// 话题 pk 活动获得
        /// </summary>
        TopicActivity = 2,
        /// <summary>
        /// 玩家关卡获得
        /// </summary>
        PlayerStage = 3,
    }

} 

