
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ClientCfg.cfg
{ 
    [System.Flags]
    public enum EGuideType
    {
        /// <summary>
        ///  没有引导
        /// </summary>
        None = 0,
        /// <summary>
        /// 通过引导关卡
        /// </summary>
        PassGuideStage = 1,
        /// <summary>
        /// 通过验证
        /// </summary>
        Authorized = 2,
        /// <summary>
        /// 通过新手关
        /// </summary>
        PassNewbieStage = 4,
        /// <summary>
        /// 初始保存玩家形象
        /// </summary>
        InitSkinImage = 8,
        /// <summary>
        /// 公众号免费皮肤
        /// </summary>
        OfficialFreeSkin = 16,
        /// <summary>
        /// ugc功能解锁
        /// </summary>
        UgcUnlock = 32,
    }

} 

