
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ClientCfg.cfg
{ 
    public enum EItemType
    {
        /// <summary>
        /// 装扮
        /// </summary>
        DressUp = 1,
        /// <summary>
        /// 版子
        /// </summary>
        Plank = 2,
        /// <summary>
        /// 随机奖励
        /// </summary>
        RandomReward = 3,
    }

} 

