
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ClientCfg.cfg
{ 
    public enum EStageType
    {
        /// <summary>
        /// 官方关卡
        /// </summary>
        Official = 1,
        /// <summary>
        /// 玩家关卡
        /// </summary>
        Player = 2,
        /// <summary>
        /// 隐藏关卡
        /// </summary>
        Hidden = 3,
    }

} 

