
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ClientCfg.cfg
{ 
    public enum ETopicType
    {
        /// <summary>
        /// 无主题
        /// </summary>
        NoTopic = -1,
        /// <summary>
        /// 默认主题
        /// </summary>
        Default = 0,
    }

} 

