
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ClientCfg.cfg
{ 
    public enum FunctionType
    {
        /// <summary>
        /// 玩家基础
        /// </summary>
        PlayerBase = 1,
        /// <summary>
        /// 关卡
        /// </summary>
        Level = 2,
        /// <summary>
        /// 剪影
        /// </summary>
        Cucoloris = 3,
        /// <summary>
        /// 星星宝箱
        /// </summary>
        StarBox = 4,
    }

} 

