
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public sealed partial class GDCommonData : Luban.BeanBase
{
    public GDCommonData(JSONNode _buf) 
    {
        { if(!_buf["InitCardBox"].IsNumber) { throw new SerializationException(); }  InitCardBox = _buf["InitCardBox"]; }
        { if(!_buf["ColorNum"].IsNumber) { throw new SerializationException(); }  ColorNum = _buf["ColorNum"]; }
        { if(!_buf["WheelSlotNum"].IsNumber) { throw new SerializationException(); }  WheelSlotNum = _buf["WheelSlotNum"]; }
    }

    public static GDCommonData DeserializeGDCommonData(JSONNode _buf)
    {
        return new cfg.GDCommonData(_buf);
    }

    /// <summary>
    /// 初始卡包
    /// </summary>
    public readonly int InitCardBox;
    /// <summary>
    /// 卡牌颜色数
    /// </summary>
    public readonly int ColorNum;
    /// <summary>
    /// 轮盘位置数
    /// </summary>
    public readonly int WheelSlotNum;
   
    public const int __ID__ = 822428220;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "InitCardBox:" + InitCardBox + ","
        + "ColorNum:" + ColorNum + ","
        + "WheelSlotNum:" + WheelSlotNum + ","
        + "}";
    }
}

}
