
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public partial class GDCommon
{

     private readonly cfg.GDCommonData _data;

     public cfg.GDCommonData Data => _data;

    public GDCommon(JSONNode _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_buf[0].IsObject) { throw new SerializationException(); }  _data = cfg.GDCommonData.DeserializeGDCommonData(_buf[0]);  }
    }


    /// <summary>
    /// 初始卡包
    /// </summary>
     public int InitCardBox => _data.InitCardBox;
    /// <summary>
    /// 卡牌颜色数
    /// </summary>
     public int ColorNum => _data.ColorNum;
    /// <summary>
    /// 轮盘位置数
    /// </summary>
     public int WheelSlotNum => _data.WheelSlotNum;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

