
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public sealed partial class GDJourneyStarData : Luban.BeanBase
{
    public GDJourneyStarData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["choose"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Choose = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Choose[__index0++] = __v0; }   }
        { var __json0 = _buf["combo"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Combo = new float[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Combo[__index0++] = __v0; }   }
    }

    public static GDJourneyStarData DeserializeGDJourneyStarData(JSONNode _buf)
    {
        return new cfg.GDJourneyStarData(_buf);
    }

    /// <summary>
    /// 游戏文本
    /// </summary>
    public readonly int Id;
    public readonly int[] Choose;
    public readonly float[] Combo;
   
    public const int __ID__ = -1632710827;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "choose:" + Luban.StringUtil.CollectionToString(Choose) + ","
        + "combo:" + Luban.StringUtil.CollectionToString(Combo) + ","
        + "}";
    }
}

}
