
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public partial class GDJourneyFunction
{
    private readonly System.Collections.Generic.Dictionary<cfg.FunctionType, cfg.GDJourneyFunctionData> _dataMap;
    private readonly System.Collections.Generic.List<cfg.GDJourneyFunctionData> _dataList;
    
    public GDJourneyFunction(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<cfg.FunctionType, cfg.GDJourneyFunctionData>();
        _dataList = new System.Collections.Generic.List<cfg.GDJourneyFunctionData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            cfg.GDJourneyFunctionData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = cfg.GDJourneyFunctionData.DeserializeGDJourneyFunctionData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.FunctionType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<cfg.FunctionType, cfg.GDJourneyFunctionData> DataMap => _dataMap;
    public System.Collections.Generic.List<cfg.GDJourneyFunctionData> DataList => _dataList;

    public cfg.GDJourneyFunctionData GetOrDefault(cfg.FunctionType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public cfg.GDJourneyFunctionData Get(cfg.FunctionType key) => _dataMap[key];
    public cfg.GDJourneyFunctionData this[cfg.FunctionType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

