
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public partial class GDJourneyCommon
{

     private readonly cfg.GDJourneyCommonData _data;

     public cfg.GDJourneyCommonData Data => _data;

    public GDJourneyCommon(JSONNode _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_buf[0].IsObject) { throw new SerializationException(); }  _data = cfg.GDJourneyCommonData.DeserializeGDJourneyCommonData(_buf[0]);  }
    }


    /// <summary>
    /// 玩家体力上限
    /// </summary>
     public int PlayerEnergyLimit => _data.PlayerEnergyLimit;
    /// <summary>
    /// 玩家体力恢复间隔(s)
    /// </summary>
     public int PlayerEnergyRecoverInterval => _data.PlayerEnergyRecoverInterval;
    /// <summary>
    /// 玩家初始体力
    /// </summary>
     public int PlayerInitEnergy => _data.PlayerInitEnergy;
    /// <summary>
    /// 玩家初始金币
    /// </summary>
     public int PlayerInitGold => _data.PlayerInitGold;
    /// <summary>
    /// 体力补给奖励
    /// </summary>
     public System.Collections.Generic.List<ItemCfg> ActivityEnergySupplyRewards => _data.ActivityEnergySupplyRewards;
    /// <summary>
    /// 金币补给奖励
    /// </summary>
     public System.Collections.Generic.List<ItemCfg> ActivityGoldSupplyRewards => _data.ActivityGoldSupplyRewards;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

