
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public sealed partial class GDJourneyCommonData : Luban.BeanBase
{
    public GDJourneyCommonData(JSONNode _buf) 
    {
        { if(!_buf["PlayerEnergyLimit"].IsNumber) { throw new SerializationException(); }  PlayerEnergyLimit = _buf["PlayerEnergyLimit"]; }
        { if(!_buf["PlayerEnergyRecoverInterval"].IsNumber) { throw new SerializationException(); }  PlayerEnergyRecoverInterval = _buf["PlayerEnergyRecoverInterval"]; }
        { if(!_buf["PlayerInitEnergy"].IsNumber) { throw new SerializationException(); }  PlayerInitEnergy = _buf["PlayerInitEnergy"]; }
        { if(!_buf["PlayerInitGold"].IsNumber) { throw new SerializationException(); }  PlayerInitGold = _buf["PlayerInitGold"]; }
        { var __json0 = _buf["ActivityEnergySupplyRewards"]; if(!__json0.IsArray) { throw new SerializationException(); } ActivityEnergySupplyRewards = new System.Collections.Generic.List<ItemCfg>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemCfg __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemCfg.DeserializeItemCfg(__e0);  }  ActivityEnergySupplyRewards.Add(__v0); }   }
        { var __json0 = _buf["ActivityGoldSupplyRewards"]; if(!__json0.IsArray) { throw new SerializationException(); } ActivityGoldSupplyRewards = new System.Collections.Generic.List<ItemCfg>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemCfg __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemCfg.DeserializeItemCfg(__e0);  }  ActivityGoldSupplyRewards.Add(__v0); }   }
    }

    public static GDJourneyCommonData DeserializeGDJourneyCommonData(JSONNode _buf)
    {
        return new cfg.GDJourneyCommonData(_buf);
    }

    /// <summary>
    /// 玩家体力上限
    /// </summary>
    public readonly int PlayerEnergyLimit;
    /// <summary>
    /// 玩家体力恢复间隔(s)
    /// </summary>
    public readonly int PlayerEnergyRecoverInterval;
    /// <summary>
    /// 玩家初始体力
    /// </summary>
    public readonly int PlayerInitEnergy;
    /// <summary>
    /// 玩家初始金币
    /// </summary>
    public readonly int PlayerInitGold;
    /// <summary>
    /// 体力补给奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemCfg> ActivityEnergySupplyRewards;
    /// <summary>
    /// 金币补给奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemCfg> ActivityGoldSupplyRewards;
   
    public const int __ID__ = -1537485778;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "PlayerEnergyLimit:" + PlayerEnergyLimit + ","
        + "PlayerEnergyRecoverInterval:" + PlayerEnergyRecoverInterval + ","
        + "PlayerInitEnergy:" + PlayerInitEnergy + ","
        + "PlayerInitGold:" + PlayerInitGold + ","
        + "ActivityEnergySupplyRewards:" + Luban.StringUtil.CollectionToString(ActivityEnergySupplyRewards) + ","
        + "ActivityGoldSupplyRewards:" + Luban.StringUtil.CollectionToString(ActivityGoldSupplyRewards) + ","
        + "}";
    }
}

}
