
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public sealed partial class GDJourneyLevelData : Luban.BeanBase
{
    public GDJourneyLevelData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["previousId"].IsNumber) { throw new SerializationException(); }  PreviousId = _buf["previousId"]; }
        { if(!_buf["chapter"].IsNumber) { throw new SerializationException(); }  Chapter = _buf["chapter"]; }
        { if(!_buf["order"].IsNumber) { throw new SerializationException(); }  Order = _buf["order"]; }
        { var __json0 = _buf["score"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Score = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Score[__index0++] = __v0; }   }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["score_id"].IsNumber) { throw new SerializationException(); }  ScoreId = _buf["score_id"]; }
        { var __json0 = _buf["souvenir"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Souvenir = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Souvenir[__index0++] = __v0; }   }
        { var __json0 = _buf["unlockCost"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockCost = new System.Collections.Generic.List<ItemCfg>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemCfg __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemCfg.DeserializeItemCfg(__e0);  }  UnlockCost.Add(__v0); }   }
        { var __json0 = _buf["enterCost"]; if(!__json0.IsArray) { throw new SerializationException(); } EnterCost = new System.Collections.Generic.List<ItemCfg>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemCfg __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemCfg.DeserializeItemCfg(__e0);  }  EnterCost.Add(__v0); }   }
        { var __json0 = _buf["dropReward"]; if(!__json0.IsArray) { throw new SerializationException(); } DropReward = new System.Collections.Generic.List<ItemDropCfg>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemDropCfg __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemDropCfg.DeserializeItemDropCfg(__e0);  }  DropReward.Add(__v0); }   }
    }

    public static GDJourneyLevelData DeserializeGDJourneyLevelData(JSONNode _buf)
    {
        return new cfg.GDJourneyLevelData(_buf);
    }

    /// <summary>
    /// 关卡id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 前置关卡ID
    /// </summary>
    public readonly int PreviousId;
    /// <summary>
    /// 关卡章节
    /// </summary>
    public readonly int Chapter;
    /// <summary>
    /// 章节内顺序
    /// </summary>
    public readonly int Order;
    public readonly int[] Score;
    /// <summary>
    /// 关卡名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 得分组id
    /// </summary>
    public readonly int ScoreId;
    public readonly int[] Souvenir;
    /// <summary>
    /// 解锁消耗
    /// </summary>
    public readonly System.Collections.Generic.List<ItemCfg> UnlockCost;
    /// <summary>
    /// 进入消耗
    /// </summary>
    public readonly System.Collections.Generic.List<ItemCfg> EnterCost;
    /// <summary>
    /// 掉落的奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemDropCfg> DropReward;
   
    public const int __ID__ = 1442088501;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        foreach (var _e in DropReward) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "previousId:" + PreviousId + ","
        + "chapter:" + Chapter + ","
        + "order:" + Order + ","
        + "score:" + Luban.StringUtil.CollectionToString(Score) + ","
        + "name:" + Name + ","
        + "scoreId:" + ScoreId + ","
        + "souvenir:" + Luban.StringUtil.CollectionToString(Souvenir) + ","
        + "unlockCost:" + Luban.StringUtil.CollectionToString(UnlockCost) + ","
        + "enterCost:" + Luban.StringUtil.CollectionToString(EnterCost) + ","
        + "dropReward:" + Luban.StringUtil.CollectionToString(DropReward) + ","
        + "}";
    }
}

}
