
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public sealed partial class GDJourneyFunctionData : Luban.BeanBase
{
    public GDJourneyFunctionData(JSONNode _buf) 
    {
        { if(!_buf["functionType"].IsNumber) { throw new SerializationException(); }  FunctionType = (cfg.FunctionType)_buf["functionType"].AsInt; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["levelId"].IsNumber) { throw new SerializationException(); }  LevelId = _buf["levelId"]; }
    }

    public static GDJourneyFunctionData DeserializeGDJourneyFunctionData(JSONNode _buf)
    {
        return new cfg.GDJourneyFunctionData(_buf);
    }

    /// <summary>
    /// 功能类型
    /// </summary>
    public readonly cfg.FunctionType FunctionType;
    /// <summary>
    /// 玩家等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int LevelId;
   
    public const int __ID__ = 61752667;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "functionType:" + FunctionType + ","
        + "level:" + Level + ","
        + "levelId:" + LevelId + ","
        + "}";
    }
}

}
