
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public partial class GDJourneyItem
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.GDJourneyItemData> _dataMap;
    private readonly System.Collections.Generic.List<cfg.GDJourneyItemData> _dataList;
    
    public GDJourneyItem(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.GDJourneyItemData>();
        _dataList = new System.Collections.Generic.List<cfg.GDJourneyItemData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            cfg.GDJourneyItemData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = cfg.GDJourneyItemData.DeserializeGDJourneyItemData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, cfg.GDJourneyItemData> DataMap => _dataMap;
    public System.Collections.Generic.List<cfg.GDJourneyItemData> DataList => _dataList;

    public cfg.GDJourneyItemData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public cfg.GDJourneyItemData Get(int key) => _dataMap[key];
    public cfg.GDJourneyItemData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

