
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public sealed partial class GDJourneyChapterData : Luban.BeanBase
{
    public GDJourneyChapterData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["level"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Level = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Level[__index0++] = __v0; }   }
    }

    public static GDJourneyChapterData DeserializeGDJourneyChapterData(JSONNode _buf)
    {
        return new cfg.GDJourneyChapterData(_buf);
    }

    /// <summary>
    /// 关卡章节
    /// </summary>
    public readonly int Id;
    public readonly int[] Level;
   
    public const int __ID__ = 2032745662;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "level:" + Luban.StringUtil.CollectionToString(Level) + ","
        + "}";
    }
}

}
