
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public partial class GDJourneyScore
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.GDJourneyScoreData> _dataMap;
    private readonly System.Collections.Generic.List<cfg.GDJourneyScoreData> _dataList;
    
    public GDJourneyScore(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.GDJourneyScoreData>();
        _dataList = new System.Collections.Generic.List<cfg.GDJourneyScoreData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            cfg.GDJourneyScoreData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = cfg.GDJourneyScoreData.DeserializeGDJourneyScoreData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, cfg.GDJourneyScoreData> DataMap => _dataMap;
    public System.Collections.Generic.List<cfg.GDJourneyScoreData> DataList => _dataList;

    public cfg.GDJourneyScoreData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public cfg.GDJourneyScoreData Get(int key) => _dataMap[key];
    public cfg.GDJourneyScoreData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

