
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public sealed partial class GDJourneyCucolorisLevelData : Luban.BeanBase
{
    public GDJourneyCucolorisLevelData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["stepCount"].IsNumber) { throw new SerializationException(); }  StepCount = _buf["stepCount"]; }
        { var __json0 = _buf["enterCost"]; if(!__json0.IsArray) { throw new SerializationException(); } EnterCost = new System.Collections.Generic.List<ItemCfg>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemCfg __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemCfg.DeserializeItemCfg(__e0);  }  EnterCost.Add(__v0); }   }
    }

    public static GDJourneyCucolorisLevelData DeserializeGDJourneyCucolorisLevelData(JSONNode _buf)
    {
        return new cfg.GDJourneyCucolorisLevelData(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡步长数量
    /// </summary>
    public readonly int StepCount;
    /// <summary>
    /// 进入消耗
    /// </summary>
    public readonly System.Collections.Generic.List<ItemCfg> EnterCost;
   
    public const int __ID__ = 1980323692;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "stepCount:" + StepCount + ","
        + "enterCost:" + Luban.StringUtil.CollectionToString(EnterCost) + ","
        + "}";
    }
}

}
