
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public sealed partial class GDJourneyCucolorisLevelStepData : Luban.BeanBase
{
    public GDJourneyCucolorisLevelStepData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["durationSecond"].IsNumber) { throw new SerializationException(); }  DurationSecond = _buf["durationSecond"]; }
        { if(!_buf["reviveSecond"].IsNumber) { throw new SerializationException(); }  ReviveSecond = _buf["reviveSecond"]; }
        { if(!_buf["searchItemCount"].IsNumber) { throw new SerializationException(); }  SearchItemCount = _buf["searchItemCount"]; }
        { var __json0 = _buf["reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.List<ItemCfg>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemCfg __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemCfg.DeserializeItemCfg(__e0);  }  Reward.Add(__v0); }   }
        { var __json0 = _buf["dropReward"]; if(!__json0.IsArray) { throw new SerializationException(); } DropReward = new System.Collections.Generic.List<ItemDropCfg>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemDropCfg __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemDropCfg.DeserializeItemDropCfg(__e0);  }  DropReward.Add(__v0); }   }
        { var __json0 = _buf["tipsCost"]; if(!__json0.IsArray) { throw new SerializationException(); } TipsCost = new System.Collections.Generic.List<ItemCfg>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemCfg __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemCfg.DeserializeItemCfg(__e0);  }  TipsCost.Add(__v0); }   }
    }

    public static GDJourneyCucolorisLevelStepData DeserializeGDJourneyCucolorisLevelStepData(JSONNode _buf)
    {
        return new cfg.GDJourneyCucolorisLevelStepData(_buf);
    }

    /// <summary>
    /// ID（cucolorLevelId*10000+步长）
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 计时秒数
    /// </summary>
    public readonly int DurationSecond;
    /// <summary>
    /// 复活增加秒数
    /// </summary>
    public readonly int ReviveSecond;
    /// <summary>
    /// 寻找物品数量
    /// </summary>
    public readonly int SearchItemCount;
    /// <summary>
    /// 固定奖励(道具ID=数量)
    /// </summary>
    public readonly System.Collections.Generic.List<ItemCfg> Reward;
    /// <summary>
    /// 掉落的奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemDropCfg> DropReward;
    /// <summary>
    /// 提示消耗(道具ID=数量)
    /// </summary>
    public readonly System.Collections.Generic.List<ItemCfg> TipsCost;
   
    public const int __ID__ = 68868952;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        foreach (var _e in DropReward) { _e?.ResolveRef(tables); }
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "durationSecond:" + DurationSecond + ","
        + "reviveSecond:" + ReviveSecond + ","
        + "searchItemCount:" + SearchItemCount + ","
        + "reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "dropReward:" + Luban.StringUtil.CollectionToString(DropReward) + ","
        + "tipsCost:" + Luban.StringUtil.CollectionToString(TipsCost) + ","
        + "}";
    }
}

}
