
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public partial class GDLanguage
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.GDLanguageData> _dataMap;
    private readonly System.Collections.Generic.List<cfg.GDLanguageData> _dataList;
    
    public GDLanguage(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.GDLanguageData>();
        _dataList = new System.Collections.Generic.List<cfg.GDLanguageData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            cfg.GDLanguageData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = cfg.GDLanguageData.DeserializeGDLanguageData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, cfg.GDLanguageData> DataMap => _dataMap;
    public System.Collections.Generic.List<cfg.GDLanguageData> DataList => _dataList;

    public cfg.GDLanguageData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public cfg.GDLanguageData Get(string key) => _dataMap[key];
    public cfg.GDLanguageData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

