
//------------------------------------------------------------------------------
// <auto-generated>
//   打包工具会修改该文件，手动修改内容可能会丢失修改
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable once CheckNamespace
namespace Sdk.Runtime.Base   
{
    /// <summary>
    /// 游戏版本号
    /// </summary>
    public static class GameVersion
    {
        public const string GameVer = "55";

        public const LaunchSettings.EnvironmentType GameEnv = LaunchSettings.EnvironmentType.Beta;
    }
}
