
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg
{
/// <summary>
/// 道具掉落
/// </summary>
public sealed partial class ItemDropCfg : Luban.BeanBase
{
    public ItemDropCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
    }

    public static ItemDropCfg DeserializeItemDropCfg(JSONNode _buf)
    {
        return new ItemDropCfg(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly long Count;
    /// <summary>
    /// 权重，万分比
    /// </summary>
    public readonly int Weight;
   
    public const int __ID__ = -1235322814;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "count:" + Count + ","
        + "weight:" + Weight + ","
        + "}";
    }
}

}
