
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg
{
public sealed partial class music_part : Luban.BeanBase
{
    public music_part(JSONNode _buf) 
    {
        { if(!_buf["time"].IsNumber) { throw new SerializationException(); }  Time = _buf["time"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static music_part Deserializemusic_part(JSONNode _buf)
    {
        return new music_part(_buf);
    }

    public readonly float Time;
    public readonly string Desc;
   
    public const int __ID__ = -780124723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "time:" + Time + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}
