
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg
{
public sealed partial class music : Luban.BeanBase
{
    public music(JSONNode _buf) 
    {
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["part"]; if(!__json0.IsArray) { throw new SerializationException(); } Part = new System.Collections.Generic.List<music_part>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { music_part __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = music_part.Deserializemusic_part(__e0);  }  Part.Add(__v0); }   }
    }

    public static music Deserializemusic(JSONNode _buf)
    {
        return new music(_buf);
    }

    public readonly string Name;
    public readonly System.Collections.Generic.List<music_part> Part;
   
    public const int __ID__ = 104263205;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        foreach (var _e in Part) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "name:" + Name + ","
        + "part:" + Luban.StringUtil.CollectionToString(Part) + ","
        + "}";
    }
}

}
