
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace ClientCfg
{
public partial class Tables
{
    public cfg.GDCommon GDCommon {get; }
    public cfg.GDCardColor GDCardColor {get; }
    public cfg.GDCardScore GDCardScore {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        GDCommon = new cfg.GDCommon(loader("cfg_gdcommon"));
        GDCardColor = new cfg.GDCardColor(loader("cfg_gdcardcolor"));
        GDCardScore = new cfg.GDCardScore(loader("cfg_gdcardscore"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GDCommon.ResolveRef(this);
        GDCardColor.ResolveRef(this);
        GDCardScore.ResolveRef(this);
    }
}

}
