
// <auto-generated>
//     Generated by the ui framework.  DO NOT EDIT!
//     Source: ChooseScreenSource.prefab
//     Remark: 可以另写一个文件来扩展此类来实现具体的与 UI 相关的逻辑, 如 OnOpen(), OnClose() 等
// </auto-generated>

using UIFramework.Base;
using UIFramework.UIScreen;
using UnityEngine;
// ReSharper disable once CheckNamespace
namespace MyUI
{
    /// <summary>
    /// Choose 的 Presenter 类   
    /// </summary>
    public sealed partial class ChooseScreenPresenter : GenericScreenPresenterBase<ChooseScreenView>
    {
        
    }
}
