// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: level.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ClientProto {

  /// <summary>Holder for reflection information generated from level.proto</summary>
  public static partial class LevelReflection {

    #region Descriptor
    /// <summary>File descriptor for level.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LevelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtsZXZlbC5wcm90bxILQ2xpZW50UHJvdG8aDGNvbW1vbi5wcm90byI0CgpM",
            "ZXZlbHNJbmZvEiYKBmxldmVscxgBIAMoCzIWLkNsaWVudFByb3RvLkxldmVs",
            "SW5mbyKYAQoJTGV2ZWxJbmZvEgoKAmlkGAEgASgFEgwKBHN0YXIYAiABKAUS",
            "GAoQYWNjdW11bGF0ZWRTY29yZRgDIAEoAxIUCgxoaXN0b3J5U2NvcmUYBCAB",
            "KAMSFQoNc291dmVuaXJDb3VudBgFIAEoBRIqCgVyYW5rcxgKIAMoCzIbLkNs",
            "aWVudFByb3RvLlJhbmtQbGF5ZXJJbmZvIjwKEkxldmVsVW5sb2NrUmVxdWVz",
            "dBIKCgJpZBgBIAEoBSIaCgFOEggKBHplcm8QABILCgZPcENvZGUQ208i7QEK",
            "E0xldmVsVW5sb2NrUmVzcG9uc2USPQoJZXJyb3JDb2RlGAEgASgOMiouQ2xp",
            "ZW50UHJvdG8uTGV2ZWxVbmxvY2tSZXNwb25zZS5FcnJvckNvZGUSKQoKZmlu",
            "YWxJdGVtcxgCIAMoCzIVLkNsaWVudFByb3RvLkl0ZW1JbmZvIhoKAU4SCAoE",
            "emVybxAAEgsKBk9wQ29kZRDcTyJQCglFcnJvckNvZGUSCwoHU3VjY2VzcxAA",
            "EhAKDExldmVsSWRFcnJvchABEhEKDUdvbGROb3RFbm91Z2gQAhIRCg1BbHJl",
            "YWR5VW5sb2NrEAMiOwoRTGV2ZWxFbnRlclJlcXVlc3QSCgoCaWQYASABKAUi",
            "GgoBThIICgR6ZXJvEAASCwoGT3BDb2RlENlPIvUCChJMZXZlbEVudGVyUmVz",
            "cG9uc2USPAoJZXJyb3JDb2RlGAEgASgOMikuQ2xpZW50UHJvdG8uTGV2ZWxF",
            "bnRlclJlc3BvbnNlLkVycm9yQ29kZRIpCgpmaW5hbEl0ZW1zGAIgAygLMhUu",
            "Q2xpZW50UHJvdG8uSXRlbUluZm8SEQoJbGV2ZWxTdGFyGAMgASgFEkEKCWJv",
            "eENvdW50cxgEIAMoCzIuLkNsaWVudFByb3RvLkxldmVsRW50ZXJSZXNwb25z",
            "ZS5Cb3hDb3VudHNFbnRyeRowCg5Cb3hDb3VudHNFbnRyeRILCgNrZXkYASAB",
            "KAUSDQoFdmFsdWUYAiABKAU6AjgBIhoKAU4SCAoEemVybxAAEgsKBk9wQ29k",
            "ZRDaTyJSCglFcnJvckNvZGUSCwoHU3VjY2VzcxAAEhAKDExldmVsSWRFcnJv",
            "chABEhMKD0VuZXJneU5vdEVub3VnaBACEhEKDUxldmVsTm9VbmxvY2sQAyLK",
            "AQoOTGV2ZWxFdmVudEluZm8SMwoEdHlwZRgBIAEoDjIlLkNsaWVudFByb3Rv",
            "LkxldmVsRXZlbnRJbmZvLkV2ZW50VHlwZRIMCgR0aW1lGAIgASgDEhIKCmRp",
            "ZmZpY3VsdHkYAyABKAUSEgoKY29tYm9Db3VudBgEIAEoBSJNCglFdmVudFR5",
            "cGUSEAoMQ2xpY2tTdWNjZXNzEAASDQoJQ2xpY2tGYWlsEAESCQoFUGF1c2UQ",
            "AhIKCgZSZXN1bWUQAxIICgRUaXBzEAQidAoSTGV2ZWxGaW5pc2hSZXF1ZXN0",
            "EisKBmV2ZW50cxgBIAMoCzIbLkNsaWVudFByb3RvLkxldmVsRXZlbnRJbmZv",
            "EhUKDXNvdXZlbmlyQ291bnQYAiABKAUiGgoBThIICgR6ZXJvEAASCwoGT3BD",
            "b2RlEN1PItUDChNMZXZlbEZpbmlzaFJlc3BvbnNlEj0KCWVycm9yQ29kZRgB",
            "IAEoDjIqLkNsaWVudFByb3RvLkxldmVsRmluaXNoUmVzcG9uc2UuRXJyb3JD",
            "b2RlEikKCmZpbmFsSXRlbXMYAiADKAsyFS5DbGllbnRQcm90by5JdGVtSW5m",
            "bxINCgVzY29yZRgDIAEoAxIpCglsZXZlbEluZm8YBCABKAsyFi5DbGllbnRQ",
            "cm90by5MZXZlbEluZm8SJgoHcmV3YXJkcxgFIAMoCzIVLkNsaWVudFByb3Rv",
            "Lkl0ZW1JbmZvEioKBXJhbmtzGAYgAygLMhsuQ2xpZW50UHJvdG8uUmFua1Bs",
            "YXllckluZm8SFAoMZGV0YWlsU2NvcmVzGAcgAygDIhoKAU4SCAoEemVybxAA",
            "EgsKBk9wQ29kZRDeTyKTAQoJRXJyb3JDb2RlEgsKB1N1Y2Nlc3MQABIQCgxM",
            "ZXZlbE5vdEZpbmQQARIYChRUaW1lTm90SW5TdGFydEFuZEVuZBACEhMKD0Nv",
            "bWJvQ291bnRFcnJvchADEhwKGENsaWNrU3VjY2Vzc0l0ZW1JZFJlcGVhdBAE",
            "EhoKFkNsaWNrU3VjY2Vzc0NvdW50RXJyb3IQBUIVWhMuL3Byb3RvYnVmO3By",
            "b3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ClientProto.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientProto.LevelsInfo), global::ClientProto.LevelsInfo.Parser, new[]{ "Levels" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientProto.LevelInfo), global::ClientProto.LevelInfo.Parser, new[]{ "Id", "Star", "AccumulatedScore", "HistoryScore", "SouvenirCount", "Ranks" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientProto.LevelUnlockRequest), global::ClientProto.LevelUnlockRequest.Parser, new[]{ "Id" }, null, new[]{ typeof(global::ClientProto.LevelUnlockRequest.Types.N) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientProto.LevelUnlockResponse), global::ClientProto.LevelUnlockResponse.Parser, new[]{ "ErrorCode", "FinalItems" }, null, new[]{ typeof(global::ClientProto.LevelUnlockResponse.Types.N), typeof(global::ClientProto.LevelUnlockResponse.Types.ErrorCode) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientProto.LevelEnterRequest), global::ClientProto.LevelEnterRequest.Parser, new[]{ "Id" }, null, new[]{ typeof(global::ClientProto.LevelEnterRequest.Types.N) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientProto.LevelEnterResponse), global::ClientProto.LevelEnterResponse.Parser, new[]{ "ErrorCode", "FinalItems", "LevelStar", "BoxCounts" }, null, new[]{ typeof(global::ClientProto.LevelEnterResponse.Types.N), typeof(global::ClientProto.LevelEnterResponse.Types.ErrorCode) }, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientProto.LevelEventInfo), global::ClientProto.LevelEventInfo.Parser, new[]{ "Type", "Time", "Difficulty", "ComboCount" }, null, new[]{ typeof(global::ClientProto.LevelEventInfo.Types.EventType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientProto.LevelFinishRequest), global::ClientProto.LevelFinishRequest.Parser, new[]{ "Events", "SouvenirCount" }, null, new[]{ typeof(global::ClientProto.LevelFinishRequest.Types.N) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientProto.LevelFinishResponse), global::ClientProto.LevelFinishResponse.Parser, new[]{ "ErrorCode", "FinalItems", "Score", "LevelInfo", "Rewards", "Ranks", "DetailScores" }, null, new[]{ typeof(global::ClientProto.LevelFinishResponse.Types.N), typeof(global::ClientProto.LevelFinishResponse.Types.ErrorCode) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 大厅关卡数据
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LevelsInfo : pb::IMessage<LevelsInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LevelsInfo> _parser = new pb::MessageParser<LevelsInfo>(() => new LevelsInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LevelsInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientProto.LevelReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelsInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelsInfo(LevelsInfo other) : this() {
      levels_ = other.levels_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelsInfo Clone() {
      return new LevelsInfo(this);
    }

    /// <summary>Field number for the "levels" field.</summary>
    public const int LevelsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ClientProto.LevelInfo> _repeated_levels_codec
        = pb::FieldCodec.ForMessage(10, global::ClientProto.LevelInfo.Parser);
    private readonly pbc::RepeatedField<global::ClientProto.LevelInfo> levels_ = new pbc::RepeatedField<global::ClientProto.LevelInfo>();
    /// <summary>
    ///已解锁关卡
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ClientProto.LevelInfo> Levels {
      get { return levels_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LevelsInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LevelsInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!levels_.Equals(other.levels_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= levels_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      levels_.WriteTo(output, _repeated_levels_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      levels_.WriteTo(ref output, _repeated_levels_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += levels_.CalculateSize(_repeated_levels_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LevelsInfo other) {
      if (other == null) {
        return;
      }
      levels_.Add(other.levels_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            levels_.AddEntriesFrom(input, _repeated_levels_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            levels_.AddEntriesFrom(ref input, _repeated_levels_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 关卡信息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LevelInfo : pb::IMessage<LevelInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LevelInfo> _parser = new pb::MessageParser<LevelInfo>(() => new LevelInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LevelInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientProto.LevelReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelInfo(LevelInfo other) : this() {
      id_ = other.id_;
      star_ = other.star_;
      accumulatedScore_ = other.accumulatedScore_;
      historyScore_ = other.historyScore_;
      souvenirCount_ = other.souvenirCount_;
      ranks_ = other.ranks_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelInfo Clone() {
      return new LevelInfo(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    /// 配置ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "star" field.</summary>
    public const int StarFieldNumber = 2;
    private int star_;
    /// <summary>
    /// 星星数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Star {
      get { return star_; }
      set {
        star_ = value;
      }
    }

    /// <summary>Field number for the "accumulatedScore" field.</summary>
    public const int AccumulatedScoreFieldNumber = 3;
    private long accumulatedScore_;
    /// <summary>
    /// 累计得分
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AccumulatedScore {
      get { return accumulatedScore_; }
      set {
        accumulatedScore_ = value;
      }
    }

    /// <summary>Field number for the "historyScore" field.</summary>
    public const int HistoryScoreFieldNumber = 4;
    private long historyScore_;
    /// <summary>
    /// 历史最高分
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long HistoryScore {
      get { return historyScore_; }
      set {
        historyScore_ = value;
      }
    }

    /// <summary>Field number for the "souvenirCount" field.</summary>
    public const int SouvenirCountFieldNumber = 5;
    private int souvenirCount_;
    /// <summary>
    /// 纪念品个数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SouvenirCount {
      get { return souvenirCount_; }
      set {
        souvenirCount_ = value;
      }
    }

    /// <summary>Field number for the "ranks" field.</summary>
    public const int RanksFieldNumber = 10;
    private static readonly pb::FieldCodec<global::ClientProto.RankPlayerInfo> _repeated_ranks_codec
        = pb::FieldCodec.ForMessage(82, global::ClientProto.RankPlayerInfo.Parser);
    private readonly pbc::RepeatedField<global::ClientProto.RankPlayerInfo> ranks_ = new pbc::RepeatedField<global::ClientProto.RankPlayerInfo>();
    /// <summary>
    ///获得完所有纪念品后只发送前3名的排行
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ClientProto.RankPlayerInfo> Ranks {
      get { return ranks_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LevelInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LevelInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Star != other.Star) return false;
      if (AccumulatedScore != other.AccumulatedScore) return false;
      if (HistoryScore != other.HistoryScore) return false;
      if (SouvenirCount != other.SouvenirCount) return false;
      if(!ranks_.Equals(other.ranks_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Star != 0) hash ^= Star.GetHashCode();
      if (AccumulatedScore != 0L) hash ^= AccumulatedScore.GetHashCode();
      if (HistoryScore != 0L) hash ^= HistoryScore.GetHashCode();
      if (SouvenirCount != 0) hash ^= SouvenirCount.GetHashCode();
      hash ^= ranks_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Star != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Star);
      }
      if (AccumulatedScore != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(AccumulatedScore);
      }
      if (HistoryScore != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(HistoryScore);
      }
      if (SouvenirCount != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SouvenirCount);
      }
      ranks_.WriteTo(output, _repeated_ranks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Star != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Star);
      }
      if (AccumulatedScore != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(AccumulatedScore);
      }
      if (HistoryScore != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(HistoryScore);
      }
      if (SouvenirCount != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SouvenirCount);
      }
      ranks_.WriteTo(ref output, _repeated_ranks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Star != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Star);
      }
      if (AccumulatedScore != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AccumulatedScore);
      }
      if (HistoryScore != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(HistoryScore);
      }
      if (SouvenirCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SouvenirCount);
      }
      size += ranks_.CalculateSize(_repeated_ranks_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LevelInfo other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Star != 0) {
        Star = other.Star;
      }
      if (other.AccumulatedScore != 0L) {
        AccumulatedScore = other.AccumulatedScore;
      }
      if (other.HistoryScore != 0L) {
        HistoryScore = other.HistoryScore;
      }
      if (other.SouvenirCount != 0) {
        SouvenirCount = other.SouvenirCount;
      }
      ranks_.Add(other.ranks_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Star = input.ReadInt32();
            break;
          }
          case 24: {
            AccumulatedScore = input.ReadInt64();
            break;
          }
          case 32: {
            HistoryScore = input.ReadInt64();
            break;
          }
          case 40: {
            SouvenirCount = input.ReadInt32();
            break;
          }
          case 82: {
            ranks_.AddEntriesFrom(input, _repeated_ranks_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Star = input.ReadInt32();
            break;
          }
          case 24: {
            AccumulatedScore = input.ReadInt64();
            break;
          }
          case 32: {
            HistoryScore = input.ReadInt64();
            break;
          }
          case 40: {
            SouvenirCount = input.ReadInt32();
            break;
          }
          case 82: {
            ranks_.AddEntriesFrom(ref input, _repeated_ranks_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 解锁关卡
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LevelUnlockRequest : pb::IMessage<LevelUnlockRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LevelUnlockRequest> _parser = new pb::MessageParser<LevelUnlockRequest>(() => new LevelUnlockRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LevelUnlockRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientProto.LevelReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelUnlockRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelUnlockRequest(LevelUnlockRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelUnlockRequest Clone() {
      return new LevelUnlockRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    ///关卡ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LevelUnlockRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LevelUnlockRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LevelUnlockRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the LevelUnlockRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum N {
        [pbr::OriginalName("zero")] Zero = 0,
        [pbr::OriginalName("OpCode")] OpCode = 10203,
      }

    }
    #endregion

  }

  /// <summary>
  /// 解锁关卡
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LevelUnlockResponse : pb::IMessage<LevelUnlockResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LevelUnlockResponse> _parser = new pb::MessageParser<LevelUnlockResponse>(() => new LevelUnlockResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LevelUnlockResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientProto.LevelReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelUnlockResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelUnlockResponse(LevelUnlockResponse other) : this() {
      errorCode_ = other.errorCode_;
      finalItems_ = other.finalItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelUnlockResponse Clone() {
      return new LevelUnlockResponse(this);
    }

    /// <summary>Field number for the "errorCode" field.</summary>
    public const int ErrorCodeFieldNumber = 1;
    private global::ClientProto.LevelUnlockResponse.Types.ErrorCode errorCode_ = global::ClientProto.LevelUnlockResponse.Types.ErrorCode.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientProto.LevelUnlockResponse.Types.ErrorCode ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = value;
      }
    }

    /// <summary>Field number for the "finalItems" field.</summary>
    public const int FinalItemsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ClientProto.ItemInfo> _repeated_finalItems_codec
        = pb::FieldCodec.ForMessage(18, global::ClientProto.ItemInfo.Parser);
    private readonly pbc::RepeatedField<global::ClientProto.ItemInfo> finalItems_ = new pbc::RepeatedField<global::ClientProto.ItemInfo>();
    /// <summary>
    /// 消耗后剩余的道具，用于客户端同步数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ClientProto.ItemInfo> FinalItems {
      get { return finalItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LevelUnlockResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LevelUnlockResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorCode != other.ErrorCode) return false;
      if(!finalItems_.Equals(other.finalItems_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrorCode != global::ClientProto.LevelUnlockResponse.Types.ErrorCode.Success) hash ^= ErrorCode.GetHashCode();
      hash ^= finalItems_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrorCode != global::ClientProto.LevelUnlockResponse.Types.ErrorCode.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrorCode);
      }
      finalItems_.WriteTo(output, _repeated_finalItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrorCode != global::ClientProto.LevelUnlockResponse.Types.ErrorCode.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrorCode);
      }
      finalItems_.WriteTo(ref output, _repeated_finalItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrorCode != global::ClientProto.LevelUnlockResponse.Types.ErrorCode.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorCode);
      }
      size += finalItems_.CalculateSize(_repeated_finalItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LevelUnlockResponse other) {
      if (other == null) {
        return;
      }
      if (other.ErrorCode != global::ClientProto.LevelUnlockResponse.Types.ErrorCode.Success) {
        ErrorCode = other.ErrorCode;
      }
      finalItems_.Add(other.finalItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrorCode = (global::ClientProto.LevelUnlockResponse.Types.ErrorCode) input.ReadEnum();
            break;
          }
          case 18: {
            finalItems_.AddEntriesFrom(input, _repeated_finalItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrorCode = (global::ClientProto.LevelUnlockResponse.Types.ErrorCode) input.ReadEnum();
            break;
          }
          case 18: {
            finalItems_.AddEntriesFrom(ref input, _repeated_finalItems_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the LevelUnlockResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum N {
        [pbr::OriginalName("zero")] Zero = 0,
        [pbr::OriginalName("OpCode")] OpCode = 10204,
      }

      public enum ErrorCode {
        [pbr::OriginalName("Success")] Success = 0,
        [pbr::OriginalName("LevelIdError")] LevelIdError = 1,
        [pbr::OriginalName("GoldNotEnough")] GoldNotEnough = 2,
        [pbr::OriginalName("AlreadyUnlock")] AlreadyUnlock = 3,
      }

    }
    #endregion

  }

  /// <summary>
  /// 进入关卡
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LevelEnterRequest : pb::IMessage<LevelEnterRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LevelEnterRequest> _parser = new pb::MessageParser<LevelEnterRequest>(() => new LevelEnterRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LevelEnterRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientProto.LevelReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelEnterRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelEnterRequest(LevelEnterRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelEnterRequest Clone() {
      return new LevelEnterRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    ///关卡ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LevelEnterRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LevelEnterRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LevelEnterRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the LevelEnterRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum N {
        [pbr::OriginalName("zero")] Zero = 0,
        [pbr::OriginalName("OpCode")] OpCode = 10201,
      }

    }
    #endregion

  }

  /// <summary>
  /// 进入关卡
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LevelEnterResponse : pb::IMessage<LevelEnterResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LevelEnterResponse> _parser = new pb::MessageParser<LevelEnterResponse>(() => new LevelEnterResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LevelEnterResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientProto.LevelReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelEnterResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelEnterResponse(LevelEnterResponse other) : this() {
      errorCode_ = other.errorCode_;
      finalItems_ = other.finalItems_.Clone();
      levelStar_ = other.levelStar_;
      boxCounts_ = other.boxCounts_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelEnterResponse Clone() {
      return new LevelEnterResponse(this);
    }

    /// <summary>Field number for the "errorCode" field.</summary>
    public const int ErrorCodeFieldNumber = 1;
    private global::ClientProto.LevelEnterResponse.Types.ErrorCode errorCode_ = global::ClientProto.LevelEnterResponse.Types.ErrorCode.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientProto.LevelEnterResponse.Types.ErrorCode ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = value;
      }
    }

    /// <summary>Field number for the "finalItems" field.</summary>
    public const int FinalItemsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ClientProto.ItemInfo> _repeated_finalItems_codec
        = pb::FieldCodec.ForMessage(18, global::ClientProto.ItemInfo.Parser);
    private readonly pbc::RepeatedField<global::ClientProto.ItemInfo> finalItems_ = new pbc::RepeatedField<global::ClientProto.ItemInfo>();
    /// <summary>
    /// 消耗后剩余的道具，用于客户端同步数据  
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ClientProto.ItemInfo> FinalItems {
      get { return finalItems_; }
    }

    /// <summary>Field number for the "levelStar" field.</summary>
    public const int LevelStarFieldNumber = 3;
    private int levelStar_;
    /// <summary>
    /// 关卡5星后，服务器随机星级
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LevelStar {
      get { return levelStar_; }
      set {
        levelStar_ = value;
      }
    }

    /// <summary>Field number for the "boxCounts" field.</summary>
    public const int BoxCountsFieldNumber = 4;
    private static readonly pbc::MapField<int, int>.Codec _map_boxCounts_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 34);
    private readonly pbc::MapField<int, int> boxCounts_ = new pbc::MapField<int, int>();
    /// <summary>
    /// 随机获得宝箱数量 key 1,2,3为对应级别的宝箱，值为数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, int> BoxCounts {
      get { return boxCounts_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LevelEnterResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LevelEnterResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorCode != other.ErrorCode) return false;
      if(!finalItems_.Equals(other.finalItems_)) return false;
      if (LevelStar != other.LevelStar) return false;
      if (!BoxCounts.Equals(other.BoxCounts)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrorCode != global::ClientProto.LevelEnterResponse.Types.ErrorCode.Success) hash ^= ErrorCode.GetHashCode();
      hash ^= finalItems_.GetHashCode();
      if (LevelStar != 0) hash ^= LevelStar.GetHashCode();
      hash ^= BoxCounts.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrorCode != global::ClientProto.LevelEnterResponse.Types.ErrorCode.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrorCode);
      }
      finalItems_.WriteTo(output, _repeated_finalItems_codec);
      if (LevelStar != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(LevelStar);
      }
      boxCounts_.WriteTo(output, _map_boxCounts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrorCode != global::ClientProto.LevelEnterResponse.Types.ErrorCode.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrorCode);
      }
      finalItems_.WriteTo(ref output, _repeated_finalItems_codec);
      if (LevelStar != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(LevelStar);
      }
      boxCounts_.WriteTo(ref output, _map_boxCounts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrorCode != global::ClientProto.LevelEnterResponse.Types.ErrorCode.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorCode);
      }
      size += finalItems_.CalculateSize(_repeated_finalItems_codec);
      if (LevelStar != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LevelStar);
      }
      size += boxCounts_.CalculateSize(_map_boxCounts_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LevelEnterResponse other) {
      if (other == null) {
        return;
      }
      if (other.ErrorCode != global::ClientProto.LevelEnterResponse.Types.ErrorCode.Success) {
        ErrorCode = other.ErrorCode;
      }
      finalItems_.Add(other.finalItems_);
      if (other.LevelStar != 0) {
        LevelStar = other.LevelStar;
      }
      boxCounts_.MergeFrom(other.boxCounts_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrorCode = (global::ClientProto.LevelEnterResponse.Types.ErrorCode) input.ReadEnum();
            break;
          }
          case 18: {
            finalItems_.AddEntriesFrom(input, _repeated_finalItems_codec);
            break;
          }
          case 24: {
            LevelStar = input.ReadInt32();
            break;
          }
          case 34: {
            boxCounts_.AddEntriesFrom(input, _map_boxCounts_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrorCode = (global::ClientProto.LevelEnterResponse.Types.ErrorCode) input.ReadEnum();
            break;
          }
          case 18: {
            finalItems_.AddEntriesFrom(ref input, _repeated_finalItems_codec);
            break;
          }
          case 24: {
            LevelStar = input.ReadInt32();
            break;
          }
          case 34: {
            boxCounts_.AddEntriesFrom(ref input, _map_boxCounts_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the LevelEnterResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum N {
        [pbr::OriginalName("zero")] Zero = 0,
        [pbr::OriginalName("OpCode")] OpCode = 10202,
      }

      public enum ErrorCode {
        [pbr::OriginalName("Success")] Success = 0,
        [pbr::OriginalName("LevelIdError")] LevelIdError = 1,
        [pbr::OriginalName("EnergyNotEnough")] EnergyNotEnough = 2,
        [pbr::OriginalName("LevelNoUnlock")] LevelNoUnlock = 3,
      }

    }
    #endregion

  }

  /// <summary>
  /// 关卡事件信息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LevelEventInfo : pb::IMessage<LevelEventInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LevelEventInfo> _parser = new pb::MessageParser<LevelEventInfo>(() => new LevelEventInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LevelEventInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientProto.LevelReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelEventInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelEventInfo(LevelEventInfo other) : this() {
      type_ = other.type_;
      time_ = other.time_;
      difficulty_ = other.difficulty_;
      comboCount_ = other.comboCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelEventInfo Clone() {
      return new LevelEventInfo(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::ClientProto.LevelEventInfo.Types.EventType type_ = global::ClientProto.LevelEventInfo.Types.EventType.ClickSuccess;
    /// <summary>
    /// 事件类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientProto.LevelEventInfo.Types.EventType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 2;
    private long time_;
    /// <summary>
    /// 时间戳 s
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "difficulty" field.</summary>
    public const int DifficultyFieldNumber = 3;
    private int difficulty_;
    /// <summary>
    /// 点击物品的难度 0开始
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Difficulty {
      get { return difficulty_; }
      set {
        difficulty_ = value;
      }
    }

    /// <summary>Field number for the "comboCount" field.</summary>
    public const int ComboCountFieldNumber = 4;
    private int comboCount_;
    /// <summary>
    /// 连击次数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ComboCount {
      get { return comboCount_; }
      set {
        comboCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LevelEventInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LevelEventInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Time != other.Time) return false;
      if (Difficulty != other.Difficulty) return false;
      if (ComboCount != other.ComboCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::ClientProto.LevelEventInfo.Types.EventType.ClickSuccess) hash ^= Type.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (Difficulty != 0) hash ^= Difficulty.GetHashCode();
      if (ComboCount != 0) hash ^= ComboCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::ClientProto.LevelEventInfo.Types.EventType.ClickSuccess) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Time != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Time);
      }
      if (Difficulty != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Difficulty);
      }
      if (ComboCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ComboCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::ClientProto.LevelEventInfo.Types.EventType.ClickSuccess) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Time != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Time);
      }
      if (Difficulty != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Difficulty);
      }
      if (ComboCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ComboCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::ClientProto.LevelEventInfo.Types.EventType.ClickSuccess) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (Difficulty != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Difficulty);
      }
      if (ComboCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ComboCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LevelEventInfo other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::ClientProto.LevelEventInfo.Types.EventType.ClickSuccess) {
        Type = other.Type;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      if (other.Difficulty != 0) {
        Difficulty = other.Difficulty;
      }
      if (other.ComboCount != 0) {
        ComboCount = other.ComboCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::ClientProto.LevelEventInfo.Types.EventType) input.ReadEnum();
            break;
          }
          case 16: {
            Time = input.ReadInt64();
            break;
          }
          case 24: {
            Difficulty = input.ReadInt32();
            break;
          }
          case 32: {
            ComboCount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::ClientProto.LevelEventInfo.Types.EventType) input.ReadEnum();
            break;
          }
          case 16: {
            Time = input.ReadInt64();
            break;
          }
          case 24: {
            Difficulty = input.ReadInt32();
            break;
          }
          case 32: {
            ComboCount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the LevelEventInfo message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum EventType {
        /// <summary>
        /// 点击成功
        /// </summary>
        [pbr::OriginalName("ClickSuccess")] ClickSuccess = 0,
        /// <summary>
        /// 点击失败
        /// </summary>
        [pbr::OriginalName("ClickFail")] ClickFail = 1,
        /// <summary>
        /// 暂停
        /// </summary>
        [pbr::OriginalName("Pause")] Pause = 2,
        /// <summary>
        /// 恢复
        /// </summary>
        [pbr::OriginalName("Resume")] Resume = 3,
        /// <summary>
        /// 提示
        /// </summary>
        [pbr::OriginalName("Tips")] Tips = 4,
      }

    }
    #endregion

  }

  /// <summary>
  /// 关卡结束
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LevelFinishRequest : pb::IMessage<LevelFinishRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LevelFinishRequest> _parser = new pb::MessageParser<LevelFinishRequest>(() => new LevelFinishRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LevelFinishRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientProto.LevelReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelFinishRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelFinishRequest(LevelFinishRequest other) : this() {
      events_ = other.events_.Clone();
      souvenirCount_ = other.souvenirCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelFinishRequest Clone() {
      return new LevelFinishRequest(this);
    }

    /// <summary>Field number for the "events" field.</summary>
    public const int EventsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ClientProto.LevelEventInfo> _repeated_events_codec
        = pb::FieldCodec.ForMessage(10, global::ClientProto.LevelEventInfo.Parser);
    private readonly pbc::RepeatedField<global::ClientProto.LevelEventInfo> events_ = new pbc::RepeatedField<global::ClientProto.LevelEventInfo>();
    /// <summary>
    /// 关卡事件日志列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ClientProto.LevelEventInfo> Events {
      get { return events_; }
    }

    /// <summary>Field number for the "souvenirCount" field.</summary>
    public const int SouvenirCountFieldNumber = 2;
    private int souvenirCount_;
    /// <summary>
    /// 纪念品个数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SouvenirCount {
      get { return souvenirCount_; }
      set {
        souvenirCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LevelFinishRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LevelFinishRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!events_.Equals(other.events_)) return false;
      if (SouvenirCount != other.SouvenirCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= events_.GetHashCode();
      if (SouvenirCount != 0) hash ^= SouvenirCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      events_.WriteTo(output, _repeated_events_codec);
      if (SouvenirCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SouvenirCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      events_.WriteTo(ref output, _repeated_events_codec);
      if (SouvenirCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SouvenirCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += events_.CalculateSize(_repeated_events_codec);
      if (SouvenirCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SouvenirCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LevelFinishRequest other) {
      if (other == null) {
        return;
      }
      events_.Add(other.events_);
      if (other.SouvenirCount != 0) {
        SouvenirCount = other.SouvenirCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            events_.AddEntriesFrom(input, _repeated_events_codec);
            break;
          }
          case 16: {
            SouvenirCount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            events_.AddEntriesFrom(ref input, _repeated_events_codec);
            break;
          }
          case 16: {
            SouvenirCount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the LevelFinishRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum N {
        [pbr::OriginalName("zero")] Zero = 0,
        [pbr::OriginalName("OpCode")] OpCode = 10205,
      }

    }
    #endregion

  }

  /// <summary>
  /// 关卡结束
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LevelFinishResponse : pb::IMessage<LevelFinishResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LevelFinishResponse> _parser = new pb::MessageParser<LevelFinishResponse>(() => new LevelFinishResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LevelFinishResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientProto.LevelReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelFinishResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelFinishResponse(LevelFinishResponse other) : this() {
      errorCode_ = other.errorCode_;
      finalItems_ = other.finalItems_.Clone();
      score_ = other.score_;
      levelInfo_ = other.levelInfo_ != null ? other.levelInfo_.Clone() : null;
      rewards_ = other.rewards_.Clone();
      ranks_ = other.ranks_.Clone();
      detailScores_ = other.detailScores_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelFinishResponse Clone() {
      return new LevelFinishResponse(this);
    }

    /// <summary>Field number for the "errorCode" field.</summary>
    public const int ErrorCodeFieldNumber = 1;
    private global::ClientProto.LevelFinishResponse.Types.ErrorCode errorCode_ = global::ClientProto.LevelFinishResponse.Types.ErrorCode.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientProto.LevelFinishResponse.Types.ErrorCode ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = value;
      }
    }

    /// <summary>Field number for the "finalItems" field.</summary>
    public const int FinalItemsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ClientProto.ItemInfo> _repeated_finalItems_codec
        = pb::FieldCodec.ForMessage(18, global::ClientProto.ItemInfo.Parser);
    private readonly pbc::RepeatedField<global::ClientProto.ItemInfo> finalItems_ = new pbc::RepeatedField<global::ClientProto.ItemInfo>();
    /// <summary>
    /// 最终道具，用于客户端同步数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ClientProto.ItemInfo> FinalItems {
      get { return finalItems_; }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 3;
    private long score_;
    /// <summary>
    /// 得分
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    /// <summary>Field number for the "levelInfo" field.</summary>
    public const int LevelInfoFieldNumber = 4;
    private global::ClientProto.LevelInfo levelInfo_;
    /// <summary>
    ///当前关卡信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientProto.LevelInfo LevelInfo {
      get { return levelInfo_; }
      set {
        levelInfo_ = value;
      }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::ClientProto.ItemInfo> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(42, global::ClientProto.ItemInfo.Parser);
    private readonly pbc::RepeatedField<global::ClientProto.ItemInfo> rewards_ = new pbc::RepeatedField<global::ClientProto.ItemInfo>();
    /// <summary>
    /// 奖励道具
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ClientProto.ItemInfo> Rewards {
      get { return rewards_; }
    }

    /// <summary>Field number for the "ranks" field.</summary>
    public const int RanksFieldNumber = 6;
    private static readonly pb::FieldCodec<global::ClientProto.RankPlayerInfo> _repeated_ranks_codec
        = pb::FieldCodec.ForMessage(50, global::ClientProto.RankPlayerInfo.Parser);
    private readonly pbc::RepeatedField<global::ClientProto.RankPlayerInfo> ranks_ = new pbc::RepeatedField<global::ClientProto.RankPlayerInfo>();
    /// <summary>
    ///排行信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ClientProto.RankPlayerInfo> Ranks {
      get { return ranks_; }
    }

    /// <summary>Field number for the "detailScores" field.</summary>
    public const int DetailScoresFieldNumber = 7;
    private static readonly pb::FieldCodec<long> _repeated_detailScores_codec
        = pb::FieldCodec.ForInt64(58);
    private readonly pbc::RepeatedField<long> detailScores_ = new pbc::RepeatedField<long>();
    /// <summary>
    /// 详细得分，分别为：基础、精确度、时间、提示 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> DetailScores {
      get { return detailScores_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LevelFinishResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LevelFinishResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorCode != other.ErrorCode) return false;
      if(!finalItems_.Equals(other.finalItems_)) return false;
      if (Score != other.Score) return false;
      if (!object.Equals(LevelInfo, other.LevelInfo)) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      if(!ranks_.Equals(other.ranks_)) return false;
      if(!detailScores_.Equals(other.detailScores_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrorCode != global::ClientProto.LevelFinishResponse.Types.ErrorCode.Success) hash ^= ErrorCode.GetHashCode();
      hash ^= finalItems_.GetHashCode();
      if (Score != 0L) hash ^= Score.GetHashCode();
      if (levelInfo_ != null) hash ^= LevelInfo.GetHashCode();
      hash ^= rewards_.GetHashCode();
      hash ^= ranks_.GetHashCode();
      hash ^= detailScores_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrorCode != global::ClientProto.LevelFinishResponse.Types.ErrorCode.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrorCode);
      }
      finalItems_.WriteTo(output, _repeated_finalItems_codec);
      if (Score != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Score);
      }
      if (levelInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LevelInfo);
      }
      rewards_.WriteTo(output, _repeated_rewards_codec);
      ranks_.WriteTo(output, _repeated_ranks_codec);
      detailScores_.WriteTo(output, _repeated_detailScores_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrorCode != global::ClientProto.LevelFinishResponse.Types.ErrorCode.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrorCode);
      }
      finalItems_.WriteTo(ref output, _repeated_finalItems_codec);
      if (Score != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Score);
      }
      if (levelInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LevelInfo);
      }
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      ranks_.WriteTo(ref output, _repeated_ranks_codec);
      detailScores_.WriteTo(ref output, _repeated_detailScores_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrorCode != global::ClientProto.LevelFinishResponse.Types.ErrorCode.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorCode);
      }
      size += finalItems_.CalculateSize(_repeated_finalItems_codec);
      if (Score != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Score);
      }
      if (levelInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LevelInfo);
      }
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      size += ranks_.CalculateSize(_repeated_ranks_codec);
      size += detailScores_.CalculateSize(_repeated_detailScores_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LevelFinishResponse other) {
      if (other == null) {
        return;
      }
      if (other.ErrorCode != global::ClientProto.LevelFinishResponse.Types.ErrorCode.Success) {
        ErrorCode = other.ErrorCode;
      }
      finalItems_.Add(other.finalItems_);
      if (other.Score != 0L) {
        Score = other.Score;
      }
      if (other.levelInfo_ != null) {
        if (levelInfo_ == null) {
          LevelInfo = new global::ClientProto.LevelInfo();
        }
        LevelInfo.MergeFrom(other.LevelInfo);
      }
      rewards_.Add(other.rewards_);
      ranks_.Add(other.ranks_);
      detailScores_.Add(other.detailScores_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrorCode = (global::ClientProto.LevelFinishResponse.Types.ErrorCode) input.ReadEnum();
            break;
          }
          case 18: {
            finalItems_.AddEntriesFrom(input, _repeated_finalItems_codec);
            break;
          }
          case 24: {
            Score = input.ReadInt64();
            break;
          }
          case 34: {
            if (levelInfo_ == null) {
              LevelInfo = new global::ClientProto.LevelInfo();
            }
            input.ReadMessage(LevelInfo);
            break;
          }
          case 42: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
          case 50: {
            ranks_.AddEntriesFrom(input, _repeated_ranks_codec);
            break;
          }
          case 58:
          case 56: {
            detailScores_.AddEntriesFrom(input, _repeated_detailScores_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrorCode = (global::ClientProto.LevelFinishResponse.Types.ErrorCode) input.ReadEnum();
            break;
          }
          case 18: {
            finalItems_.AddEntriesFrom(ref input, _repeated_finalItems_codec);
            break;
          }
          case 24: {
            Score = input.ReadInt64();
            break;
          }
          case 34: {
            if (levelInfo_ == null) {
              LevelInfo = new global::ClientProto.LevelInfo();
            }
            input.ReadMessage(LevelInfo);
            break;
          }
          case 42: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
          case 50: {
            ranks_.AddEntriesFrom(ref input, _repeated_ranks_codec);
            break;
          }
          case 58:
          case 56: {
            detailScores_.AddEntriesFrom(ref input, _repeated_detailScores_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the LevelFinishResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum N {
        [pbr::OriginalName("zero")] Zero = 0,
        [pbr::OriginalName("OpCode")] OpCode = 10206,
      }

      public enum ErrorCode {
        [pbr::OriginalName("Success")] Success = 0,
        [pbr::OriginalName("LevelNotFind")] LevelNotFind = 1,
        [pbr::OriginalName("TimeNotInStartAndEnd")] TimeNotInStartAndEnd = 2,
        [pbr::OriginalName("ComboCountError")] ComboCountError = 3,
        [pbr::OriginalName("ClickSuccessItemIdRepeat")] ClickSuccessItemIdRepeat = 4,
        [pbr::OriginalName("ClickSuccessCountError")] ClickSuccessCountError = 5,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
