
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public sealed partial class GDCardScoreData : Luban.BeanBase
{
    public GDCardScoreData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["num"].IsNumber) { throw new SerializationException(); }  Num = _buf["num"]; }
        { if(!_buf["addCardBox"].IsNumber) { throw new SerializationException(); }  AddCardBox = _buf["addCardBox"]; }
        { if(!_buf["Score"].IsNumber) { throw new SerializationException(); }  Score = _buf["Score"]; }
    }

    public static GDCardScoreData DeserializeGDCardScoreData(JSONNode _buf)
    {
        return new cfg.GDCardScoreData(_buf);
    }

    /// <summary>
    /// 消除得分
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Num;
    /// <summary>
    /// 增加卡包
    /// </summary>
    public readonly int AddCardBox;
    /// <summary>
    /// 得分
    /// </summary>
    public readonly int Score;
   
    public const int __ID__ = -909611835;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "num:" + Num + ","
        + "addCardBox:" + AddCardBox + ","
        + "Score:" + Score + ","
        + "}";
    }
}

}
