
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ClientCfg.cfg
{
public partial class GDCardScore
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.GDCardScoreData> _dataMap;
    private readonly System.Collections.Generic.List<cfg.GDCardScoreData> _dataList;
    
    public GDCardScore(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.GDCardScoreData>();
        _dataList = new System.Collections.Generic.List<cfg.GDCardScoreData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            cfg.GDCardScoreData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = cfg.GDCardScoreData.DeserializeGDCardScoreData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, cfg.GDCardScoreData> DataMap => _dataMap;
    public System.Collections.Generic.List<cfg.GDCardScoreData> DataList => _dataList;

    public cfg.GDCardScoreData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public cfg.GDCardScoreData Get(int key) => _dataMap[key];
    public cfg.GDCardScoreData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

