// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: login.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest_N int32

const (
	LoginRequest_zero   LoginRequest_N = 0
	LoginRequest_OpCode LoginRequest_N = 10001
)

// Enum value maps for LoginRequest_N.
var (
	LoginRequest_N_name = map[int32]string{
		0:     "zero",
		10001: "OpCode",
	}
	LoginRequest_N_value = map[string]int32{
		"zero":   0,
		"OpCode": 10001,
	}
)

func (x LoginRequest_N) Enum() *LoginRequest_N {
	p := new(LoginRequest_N)
	*p = x
	return p
}

func (x LoginRequest_N) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginRequest_N) Descriptor() protoreflect.EnumDescriptor {
	return file_login_proto_enumTypes[0].Descriptor()
}

func (LoginRequest_N) Type() protoreflect.EnumType {
	return &file_login_proto_enumTypes[0]
}

func (x LoginRequest_N) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginRequest_N.Descriptor instead.
func (LoginRequest_N) EnumDescriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{0, 0}
}

type LoginResponse_N int32

const (
	LoginResponse_zero   LoginResponse_N = 0
	LoginResponse_OpCode LoginResponse_N = 10002
)

// Enum value maps for LoginResponse_N.
var (
	LoginResponse_N_name = map[int32]string{
		0:     "zero",
		10002: "OpCode",
	}
	LoginResponse_N_value = map[string]int32{
		"zero":   0,
		"OpCode": 10002,
	}
)

func (x LoginResponse_N) Enum() *LoginResponse_N {
	p := new(LoginResponse_N)
	*p = x
	return p
}

func (x LoginResponse_N) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResponse_N) Descriptor() protoreflect.EnumDescriptor {
	return file_login_proto_enumTypes[1].Descriptor()
}

func (LoginResponse_N) Type() protoreflect.EnumType {
	return &file_login_proto_enumTypes[1]
}

func (x LoginResponse_N) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResponse_N.Descriptor instead.
func (LoginResponse_N) EnumDescriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{1, 0}
}

type HeartBeatRequest_N int32

const (
	HeartBeatRequest_zero   HeartBeatRequest_N = 0
	HeartBeatRequest_OpCode HeartBeatRequest_N = 10003
)

// Enum value maps for HeartBeatRequest_N.
var (
	HeartBeatRequest_N_name = map[int32]string{
		0:     "zero",
		10003: "OpCode",
	}
	HeartBeatRequest_N_value = map[string]int32{
		"zero":   0,
		"OpCode": 10003,
	}
)

func (x HeartBeatRequest_N) Enum() *HeartBeatRequest_N {
	p := new(HeartBeatRequest_N)
	*p = x
	return p
}

func (x HeartBeatRequest_N) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeartBeatRequest_N) Descriptor() protoreflect.EnumDescriptor {
	return file_login_proto_enumTypes[2].Descriptor()
}

func (HeartBeatRequest_N) Type() protoreflect.EnumType {
	return &file_login_proto_enumTypes[2]
}

func (x HeartBeatRequest_N) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeartBeatRequest_N.Descriptor instead.
func (HeartBeatRequest_N) EnumDescriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{4, 0}
}

type HeartBeatResponse_N int32

const (
	HeartBeatResponse_zero   HeartBeatResponse_N = 0
	HeartBeatResponse_OpCode HeartBeatResponse_N = 10004
)

// Enum value maps for HeartBeatResponse_N.
var (
	HeartBeatResponse_N_name = map[int32]string{
		0:     "zero",
		10004: "OpCode",
	}
	HeartBeatResponse_N_value = map[string]int32{
		"zero":   0,
		"OpCode": 10004,
	}
)

func (x HeartBeatResponse_N) Enum() *HeartBeatResponse_N {
	p := new(HeartBeatResponse_N)
	*p = x
	return p
}

func (x HeartBeatResponse_N) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeartBeatResponse_N) Descriptor() protoreflect.EnumDescriptor {
	return file_login_proto_enumTypes[3].Descriptor()
}

func (HeartBeatResponse_N) Type() protoreflect.EnumType {
	return &file_login_proto_enumTypes[3]
}

func (x HeartBeatResponse_N) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeartBeatResponse_N.Descriptor instead.
func (HeartBeatResponse_N) EnumDescriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{5, 0}
}

type LoginLoadDataRequest_N int32

const (
	LoginLoadDataRequest_zero   LoginLoadDataRequest_N = 0
	LoginLoadDataRequest_OpCode LoginLoadDataRequest_N = 10003
)

// Enum value maps for LoginLoadDataRequest_N.
var (
	LoginLoadDataRequest_N_name = map[int32]string{
		0:     "zero",
		10003: "OpCode",
	}
	LoginLoadDataRequest_N_value = map[string]int32{
		"zero":   0,
		"OpCode": 10003,
	}
)

func (x LoginLoadDataRequest_N) Enum() *LoginLoadDataRequest_N {
	p := new(LoginLoadDataRequest_N)
	*p = x
	return p
}

func (x LoginLoadDataRequest_N) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginLoadDataRequest_N) Descriptor() protoreflect.EnumDescriptor {
	return file_login_proto_enumTypes[4].Descriptor()
}

func (LoginLoadDataRequest_N) Type() protoreflect.EnumType {
	return &file_login_proto_enumTypes[4]
}

func (x LoginLoadDataRequest_N) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginLoadDataRequest_N.Descriptor instead.
func (LoginLoadDataRequest_N) EnumDescriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{6, 0}
}

type LoginLoadDataResponse_N int32

const (
	LoginLoadDataResponse_zero   LoginLoadDataResponse_N = 0
	LoginLoadDataResponse_OpCode LoginLoadDataResponse_N = 10004
)

// Enum value maps for LoginLoadDataResponse_N.
var (
	LoginLoadDataResponse_N_name = map[int32]string{
		0:     "zero",
		10004: "OpCode",
	}
	LoginLoadDataResponse_N_value = map[string]int32{
		"zero":   0,
		"OpCode": 10004,
	}
)

func (x LoginLoadDataResponse_N) Enum() *LoginLoadDataResponse_N {
	p := new(LoginLoadDataResponse_N)
	*p = x
	return p
}

func (x LoginLoadDataResponse_N) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginLoadDataResponse_N) Descriptor() protoreflect.EnumDescriptor {
	return file_login_proto_enumTypes[5].Descriptor()
}

func (LoginLoadDataResponse_N) Type() protoreflect.EnumType {
	return &file_login_proto_enumTypes[5]
}

func (x LoginLoadDataResponse_N) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginLoadDataResponse_N.Descriptor instead.
func (LoginLoadDataResponse_N) EnumDescriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{7, 0}
}

type GmRequest_N int32

const (
	GmRequest_zero   GmRequest_N = 0
	GmRequest_OpCode GmRequest_N = 10005
)

// Enum value maps for GmRequest_N.
var (
	GmRequest_N_name = map[int32]string{
		0:     "zero",
		10005: "OpCode",
	}
	GmRequest_N_value = map[string]int32{
		"zero":   0,
		"OpCode": 10005,
	}
)

func (x GmRequest_N) Enum() *GmRequest_N {
	p := new(GmRequest_N)
	*p = x
	return p
}

func (x GmRequest_N) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GmRequest_N) Descriptor() protoreflect.EnumDescriptor {
	return file_login_proto_enumTypes[6].Descriptor()
}

func (GmRequest_N) Type() protoreflect.EnumType {
	return &file_login_proto_enumTypes[6]
}

func (x GmRequest_N) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GmRequest_N.Descriptor instead.
func (GmRequest_N) EnumDescriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{9, 0}
}

type GmResponse_N int32

const (
	GmResponse_zero   GmResponse_N = 0
	GmResponse_OpCode GmResponse_N = 10006
)

// Enum value maps for GmResponse_N.
var (
	GmResponse_N_name = map[int32]string{
		0:     "zero",
		10006: "OpCode",
	}
	GmResponse_N_value = map[string]int32{
		"zero":   0,
		"OpCode": 10006,
	}
)

func (x GmResponse_N) Enum() *GmResponse_N {
	p := new(GmResponse_N)
	*p = x
	return p
}

func (x GmResponse_N) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GmResponse_N) Descriptor() protoreflect.EnumDescriptor {
	return file_login_proto_enumTypes[7].Descriptor()
}

func (GmResponse_N) Type() protoreflect.EnumType {
	return &file_login_proto_enumTypes[7]
}

func (x GmResponse_N) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GmResponse_N.Descriptor instead.
func (GmResponse_N) EnumDescriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{10, 0}
}

// 统一登录请求
type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                    // 登录码（必填）
	Platform Platform `protobuf:"varint,2,opt,name=platform,proto3,enum=ClientProto.Platform" json:"platform,omitempty"` // 平台号（必填）
	Channel  string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`                              // 渠道标志（可选，渠道号）
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_UNKNOWN
}

func (x *LoginRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

// 统一登录回复
type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                           // 玩家 uid
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                       // token
	Time     int64  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`                        // token 过期时间
	Platform int32  `protobuf:"varint,4,opt,name=platform,proto3" json:"platform,omitempty"`                // 平台号
	Avatar   string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`                     // 玩家头像
	NickName string `protobuf:"bytes,6,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"` // 玩家昵称
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *LoginResponse) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *LoginResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *LoginResponse) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

// 统一逻辑请求
type LogicMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 消息二进制数据
}

func (x *LogicMsgRequest) Reset() {
	*x = LogicMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicMsgRequest) ProtoMessage() {}

func (x *LogicMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicMsgRequest.ProtoReflect.Descriptor instead.
func (*LogicMsgRequest) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{2}
}

func (x *LogicMsgRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 统一逻辑返回
type LogicMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode EHttpErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=ClientProto.EHttpErrorCode" json:"errorCode,omitempty"` // 错误码
	ErrorMsg  string         `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`                                    // 错误信息
	Data      []byte         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                            // 消息二进制数据
}

func (x *LogicMsgResponse) Reset() {
	*x = LogicMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicMsgResponse) ProtoMessage() {}

func (x *LogicMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicMsgResponse.ProtoReflect.Descriptor instead.
func (*LogicMsgResponse) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{3}
}

func (x *LogicMsgResponse) GetErrorCode() EHttpErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return EHttpErrorCode_Nil
}

func (x *LogicMsgResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *LogicMsgResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 客户端心跳请求
type HeartBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientTime int64 `protobuf:"varint,1,opt,name=clientTime,proto3" json:"clientTime,omitempty"`
}

func (x *HeartBeatRequest) Reset() {
	*x = HeartBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatRequest) ProtoMessage() {}

func (x *HeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatRequest.ProtoReflect.Descriptor instead.
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{4}
}

func (x *HeartBeatRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

// 客户端心跳请求
type HeartBeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTime int64 `protobuf:"varint,1,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{5}
}

func (x *HeartBeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 登录加载数据请求
type LoginLoadDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platform Platform `protobuf:"varint,1,opt,name=platform,proto3,enum=ClientProto.Platform" json:"platform,omitempty"` // 登录平台
}

func (x *LoginLoadDataRequest) Reset() {
	*x = LoginLoadDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginLoadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLoadDataRequest) ProtoMessage() {}

func (x *LoginLoadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLoadDataRequest.ProtoReflect.Descriptor instead.
func (*LoginLoadDataRequest) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{6}
}

func (x *LoginLoadDataRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_UNKNOWN
}

// 登录加载数据请求
type LoginLoadDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTime     int64           `protobuf:"varint,1,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	PlayerBaseInfo *PlayerBaseInfo `protobuf:"bytes,2,opt,name=playerBaseInfo,proto3" json:"playerBaseInfo,omitempty"` //玩家基础信息
}

func (x *LoginLoadDataResponse) Reset() {
	*x = LoginLoadDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginLoadDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLoadDataResponse) ProtoMessage() {}

func (x *LoginLoadDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLoadDataResponse.ProtoReflect.Descriptor instead.
func (*LoginLoadDataResponse) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{7}
}

func (x *LoginLoadDataResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *LoginLoadDataResponse) GetPlayerBaseInfo() *PlayerBaseInfo {
	if x != nil {
		return x.PlayerBaseInfo
	}
	return nil
}

// 玩家基础信息 TODO 添加其他信息
type PlayerBaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                    //玩家ID
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                // 名称
	Level       int32  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`             // 等级
	Exp         int32  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`                 // 经验
	HeadImage   string `protobuf:"bytes,5,opt,name=headImage,proto3" json:"headImage,omitempty"`      //头像
	IsNewPlayer bool   `protobuf:"varint,6,opt,name=isNewPlayer,proto3" json:"isNewPlayer,omitempty"` //是否为新玩家
}

func (x *PlayerBaseInfo) Reset() {
	*x = PlayerBaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBaseInfo) ProtoMessage() {}

func (x *PlayerBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBaseInfo.ProtoReflect.Descriptor instead.
func (*PlayerBaseInfo) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerBaseInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerBaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerBaseInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerBaseInfo) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerBaseInfo) GetHeadImage() string {
	if x != nil {
		return x.HeadImage
	}
	return ""
}

func (x *PlayerBaseInfo) GetIsNewPlayer() bool {
	if x != nil {
		return x.IsNewPlayer
	}
	return false
}

// GM请求
type GmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`   //命令 (服务器通过命令反射调用方法)
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"` //参数
}

func (x *GmRequest) Reset() {
	*x = GmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GmRequest) ProtoMessage() {}

func (x *GmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GmRequest.ProtoReflect.Descriptor instead.
func (*GmRequest) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{9}
}

func (x *GmRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *GmRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// GM请求
type GmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode EHttpErrorCode `protobuf:"varint,1,opt,name=errCode,proto3,enum=ClientProto.EHttpErrorCode" json:"errCode,omitempty"` //错误码
	ErrMsg  string         `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`                                    // 错误信息
}

func (x *GmResponse) Reset() {
	*x = GmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GmResponse) ProtoMessage() {}

func (x *GmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GmResponse.ProtoReflect.Descriptor instead.
func (*GmResponse) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{10}
}

func (x *GmResponse) GetErrCode() EHttpErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return EHttpErrorCode_Nil
}

func (x *GmResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_login_proto protoreflect.FileDescriptor

var file_login_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x31, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x1a, 0x0a, 0x01, 0x4e, 0x12,
	0x08, 0x0a, 0x04, 0x7a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x4f, 0x70, 0x43,
	0x6f, 0x64, 0x65, 0x10, 0x91, 0x4e, 0x22, 0xb8, 0x01, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x01, 0x4e, 0x12, 0x08, 0x0a, 0x04, 0x7a, 0x65,
	0x72, 0x6f, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x4f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x10, 0x92,
	0x4e, 0x22, 0x25, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7d, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x69,
	0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x48,
	0x74, 0x74, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4e, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x01, 0x4e,
	0x12, 0x08, 0x0a, 0x04, 0x7a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x4f, 0x70,
	0x43, 0x6f, 0x64, 0x65, 0x10, 0x93, 0x4e, 0x22, 0x4f, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x01,
	0x4e, 0x12, 0x08, 0x0a, 0x04, 0x7a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x4f,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x10, 0x94, 0x4e, 0x22, 0x65, 0x0a, 0x14, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x31, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x22, 0x1a, 0x0a, 0x01, 0x4e, 0x12, 0x08, 0x0a, 0x04, 0x7a, 0x65, 0x72, 0x6f,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x4f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x10, 0x93, 0x4e, 0x22,
	0x98, 0x01, 0x0a, 0x15, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x1a,
	0x0a, 0x01, 0x4e, 0x12, 0x08, 0x0a, 0x04, 0x7a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x06, 0x4f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x10, 0x94, 0x4e, 0x22, 0x9c, 0x01, 0x0a, 0x0e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x65, 0x61,
	0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x68, 0x65,
	0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x4e, 0x65, 0x77,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73,
	0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x4d, 0x0a, 0x09, 0x47, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x1a, 0x0a, 0x01,
	0x4e, 0x12, 0x08, 0x0a, 0x04, 0x7a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x4f,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x10, 0x95, 0x4e, 0x22, 0x77, 0x0a, 0x0a, 0x47, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x48, 0x74, 0x74, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x1a, 0x0a, 0x01, 0x4e, 0x12, 0x08, 0x0a, 0x04, 0x7a, 0x65,
	0x72, 0x6f, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x4f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x10, 0x96,
	0x4e, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_login_proto_rawDescOnce sync.Once
	file_login_proto_rawDescData = file_login_proto_rawDesc
)

func file_login_proto_rawDescGZIP() []byte {
	file_login_proto_rawDescOnce.Do(func() {
		file_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_login_proto_rawDescData)
	})
	return file_login_proto_rawDescData
}

var file_login_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_login_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_login_proto_goTypes = []interface{}{
	(LoginRequest_N)(0),           // 0: ClientProto.LoginRequest.N
	(LoginResponse_N)(0),          // 1: ClientProto.LoginResponse.N
	(HeartBeatRequest_N)(0),       // 2: ClientProto.HeartBeatRequest.N
	(HeartBeatResponse_N)(0),      // 3: ClientProto.HeartBeatResponse.N
	(LoginLoadDataRequest_N)(0),   // 4: ClientProto.LoginLoadDataRequest.N
	(LoginLoadDataResponse_N)(0),  // 5: ClientProto.LoginLoadDataResponse.N
	(GmRequest_N)(0),              // 6: ClientProto.GmRequest.N
	(GmResponse_N)(0),             // 7: ClientProto.GmResponse.N
	(*LoginRequest)(nil),          // 8: ClientProto.LoginRequest
	(*LoginResponse)(nil),         // 9: ClientProto.LoginResponse
	(*LogicMsgRequest)(nil),       // 10: ClientProto.LogicMsgRequest
	(*LogicMsgResponse)(nil),      // 11: ClientProto.LogicMsgResponse
	(*HeartBeatRequest)(nil),      // 12: ClientProto.HeartBeatRequest
	(*HeartBeatResponse)(nil),     // 13: ClientProto.HeartBeatResponse
	(*LoginLoadDataRequest)(nil),  // 14: ClientProto.LoginLoadDataRequest
	(*LoginLoadDataResponse)(nil), // 15: ClientProto.LoginLoadDataResponse
	(*PlayerBaseInfo)(nil),        // 16: ClientProto.PlayerBaseInfo
	(*GmRequest)(nil),             // 17: ClientProto.GmRequest
	(*GmResponse)(nil),            // 18: ClientProto.GmResponse
	(Platform)(0),                 // 19: ClientProto.Platform
	(EHttpErrorCode)(0),           // 20: ClientProto.EHttpErrorCode
}
var file_login_proto_depIdxs = []int32{
	19, // 0: ClientProto.LoginRequest.platform:type_name -> ClientProto.Platform
	20, // 1: ClientProto.LogicMsgResponse.errorCode:type_name -> ClientProto.EHttpErrorCode
	19, // 2: ClientProto.LoginLoadDataRequest.platform:type_name -> ClientProto.Platform
	16, // 3: ClientProto.LoginLoadDataResponse.playerBaseInfo:type_name -> ClientProto.PlayerBaseInfo
	20, // 4: ClientProto.GmResponse.errCode:type_name -> ClientProto.EHttpErrorCode
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_login_proto_init() }
func file_login_proto_init() {
	if File_login_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginLoadDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginLoadDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_login_proto_rawDesc,
			NumEnums:      8,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_proto_goTypes,
		DependencyIndexes: file_login_proto_depIdxs,
		EnumInfos:         file_login_proto_enumTypes,
		MessageInfos:      file_login_proto_msgTypes,
	}.Build()
	File_login_proto = out.File
	file_login_proto_rawDesc = nil
	file_login_proto_goTypes = nil
	file_login_proto_depIdxs = nil
}
